"""Read-only, authenticated checks complementing actual browser clicks."""
import json
import os
import sys
from pathlib import Path
import requests

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[2]))
if not os.environ.get('SQLCHECK_DB_NAME', '').startswith('tdsql_uat_o_'):
    raise SystemExit('Isolated UAT database required')
BASE = 'http://127.0.0.1:8002'
s = requests.Session()
r = s.post(BASE + '/api/v1/auth/login', json={'username':'admin','password':os.environ['UAT_O_PASSWORD']},timeout=10)
r.raise_for_status()
s.headers['Authorization'] = 'Bearer ' + r.json()['token']
rows = []
from backend.services.database import _get_connection
c = _get_connection()
try:
    rows.append({'database_version':dict(c.execute('SELECT VERSION() AS version').fetchone())})
    rows.append({'local_inspection_rows':dict(c.execute('SELECT COUNT(*) AS n FROM daily_inspection WHERE connection_id=?',('uat_o_local',)).fetchone())})
finally:
    c.close()
for path in ['/health','/api/v1/ppt-report/dashboard?connection_id=uat_o_local','/api/v1/gateway-log/reports?connection_id=uat_o_local','/api/v1/audit/file-reports','/api/v1/audit/extracted-reports']:
    r = s.get(BASE + path,timeout=25)
    rows.append({'endpoint':path,'status':r.status_code,'body':r.json()})
    if path.startswith('/api/v1/gateway-log/reports') and r.ok:
        for record in r.json():
            detail = s.get(BASE + '/api/v1/gateway-log/reports/' + str(record['id']),timeout=20).json()
            html = detail.get('report_html','')
            rows.append({'gateway_id':record['id'],'html_has_heading':'<h1' in html,'html_chars':len(html),'has_footer':'Generated by' in html})
            (HERE / 'gateway_report.html').write_text(html,encoding='utf-8')
    if path == '/api/v1/audit/file-reports' and r.ok:
        body = r.json()
        records = body.get('items',body.get('reports',[])) if isinstance(body,dict) else body
        for record in records[:2]:
            report_id = record['id']
            exported = s.get(BASE + f'/api/v1/audit/file-reports/{report_id}/html',timeout=20)
            rows.append({'file_report_export':report_id,'status':exported.status_code,'bytes':len(exported.content),'content_type':exported.headers.get('content-type')})
            (HERE / f'file_report_{report_id}.html').write_text(exported.text,encoding='utf-8')
for path in ['/api/v1/cluster-inspect/run','/api/v1/sql-stats/analyze']:
    r = s.post(BASE + path,json={'connection_id':'uat_o_local'},timeout=30)
    rows.append({'endpoint':path,'status':r.status_code,'body':r.json()})
r = s.get(BASE + '/api/v1/ppt-report/generate?connection_id=uat_o_local',timeout=45)
rows.append({'pdf_export_status':r.status_code,'content_type':r.headers.get('content-type'),'bytes':len(r.content),'is_pdf':r.content.startswith(b'%PDF-')})
if r.ok and r.content.startswith(b'%PDF-'):
    (HERE / 'ops_report.pdf').write_bytes(r.content)
else:
    rows[-1]['error'] = r.text[:1000]
(HERE / 'supplemental_results.json').write_text(json.dumps(rows,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps([{k:v for k,v in row.items() if k!='body'} for row in rows],ensure_ascii=False,indent=2))
